[workspace]
authors = ["Sierra Arn"]
channels = ["conda-forge"]
name = "redis-core"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]

[dependencies]
python = "*"
pydantic-settings = "*"
redis-py = "*"
just = "*"

[feature.test.dependencies]
jupyterlab = "*"

[environments]
test = ["test"]